name: CI/CD (Test + Build + Fake Deploy)

on:
  push:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Build the app
        run: npm run build

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest

    steps:
      - name: Fake Deploy Step
        run: |
          echo "✅ Starting deployment..."
          echo "✅ Build folder exists:"
          ls -la dist
          echo "✅ Deployment simulated successfully 🎉"
